format = """
[╭─](#94e2d5)\
[](#313244)\
$python\
$username\
[](bg:#45475A fg:#313244)\
$directory\
[](fg:#45475A bg:#585B70)\
$git_branch\
$git_status\
[](fg:#585B70 bg:#7287fd)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#7287fd bg:#209fb5)\
$docker_context\
[](fg:#209fb5 bg:#179299)\
$time\
$cmd_duration\
[](fg:#179299)\
[
╰](#94e2d5)\
$character\
[](#94e2d5)\
"""

command_timeout = 5000
# Disable the blank line at the start of the prompt
#add_newline = false

# You can also replace your username with a neat symbol like  to save some space

[username]
show_always = true
style_user = "bg:#313244"
style_root = "bg:#313244"
format = '[  $user ]($style)'

[directory]
style = "bg:#45475A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#7287fd"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#209fb5"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#7287fd"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#7287FD"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#585B70"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#585B70"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#7287FD"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#7287FD"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#7287FD"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#7287FD"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#7287FD"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#7287FD"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#313244"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#7287FD"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%H:%M " # Hour:Minute Format
style = "bg:#179299"
format = '[ 󰥔 $time]($style)'

[character]
success_symbol = "[ ](fg:#94e2d5)"
error_symbol = "[ ](fg:#f38ba8)"

[cmd_duration]
min_time = 1000
style = "bg:#179299"
format = '[ 󱦟 $duration ]($style)'
